[project]
name = "photoblogserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.14"
dependencies = [
    "django>=5.2.7",
    "djangorestframework>=3.16.1",
    "dotenv>=0.9.9",
    "pillow>=12.0.0",
]
